#!/usr/bin/php
<?php
if (!isset($argv[1])){
	passthru('php lib/mra.php');
	exit(0);
} else {
	switch($argv[1]) {
		case "new":
		case "-n":
		  passthru('php ./lib/mra-new.php');
		break;
		case "upload":
		case "-u":
		  echo "Not working yet: upload site to remote directory";
		break;
		case "widget":
		case "-w":
			echo "Start widget".PHP_EOL;
			passthru('./lib/mra-widget');
		break;
		default:
echo <<<EOD
Invalid command: $argv[1]
Usage: ./arrow [command]
./arrow           Build the website to the export folder.
     -n   new       Create a site.conf file and the default folders.
     -w   widget    Start the update widget.
     -u   upload    *Feature not implemented*

EOD;
	}
	exit(0);
}
?>
