#!/bin/bash

#if zenity --entry \
#--title="Create a Site" \
#--text="Enter name of new site:" \
#--entry-text "My Site"
#  then echo $?
#  else echo "No name entered"
#fi
php lib/mra.php
### command line for uploading to remot host
if [ $# -gt 0  ]; then
if [ $1 = upload ] ; then
	echo "### Uploading site"
	### by ftp
	#lftp -f _dev/lftp.conf
	### with rsync
	rsync -vrc --progress --stats -e ssh --delete /httpdocs/mrarrow/ berg@192.168.0.103:/httpdocs/mrarrow/
fi
if [ $1 = widget ] ; then
	echo "### Starting Mr Arrow widget"
	./lib/widget
fi
fi
