#!/usr/bin/php
<?php
if (!isset($argv[1])){
	passthru('php lib/mra.php');
	exit(0);
} else {
	switch($argv[1]) {
		case "new": passthru('php ./lib/mra-new.php'); break;
		case "upload": echo "upload site to remote directory"; break;
		case "widget":
			echo "Start widget".PHP_EOL;
			passthru('./lib/widget');
			break;
		default:
echo <<<EOD
Invalid command: $argv[1]
Usage: ./arrow [command]
./arrow           Build the website to the export folder.
        new       Create a site.conf file and the default folders.
        widget    Start the update widget.
        upload    Run an update and upload the result to a remote folder.

EOD;
	}
	exit(0);
}
?>
